# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:

import numpy as np
arr=np.array(5)


In [4]:
print(arr)

5


In [15]:
## assignment 1
arr=np.random.randint(1,21,(5,5))
print(f"original:\n{arr}")
arr[:,2]=1
print(f"after changing value :\n{arr}")

original:
[[ 3 13 16  8  3]
 [19  2 19  9  3]
 [ 9  6 14  5  1]
 [ 6  9 16  8 10]
 [ 4  9  9 20 11]]
after changing value :
[[ 3 13  1  8  3]
 [19  2  1  9  3]
 [ 9  6  1  5  1]
 [ 6  9  1  8 10]
 [ 4  9  1 20 11]]


In [24]:
# b
arr=np.arange(1,17)
arr=arr.reshape(4,4)
print(f"original:\n {arr}")
np.fill_diagonal(arr,0)
print(f"after replacing :\n{arr}")


original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
after replacing :
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
# assignment 2,a
arr=np.arange(1,37)
arr=arr.reshape(6,6)
print(arr)
sub=arr[2:5,1:4]
print(sub)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [42]:
#b
arr=np.random.randint(1,50,(5,5))
print(arr)
sub=np.concatenate((arr[0],arr[-1],arr[1:-1,0],arr[1:-1,-1]))
print(sub)

[[35 11 12 30  4]
 [30 26 42 49 15]
 [46 39 27 31 40]
 [26 43 24 35 41]
 [40 37 16 30 29]]
[35 11 12 30  4 40 37 16 30 29 30 46 26 15 40 41]


In [3]:
# assignment 3 ,a
import numpy as np
arr1=np.random.randint(1,13,(3,4))
arr2=np.random.randint(1,13,(3,4))
print(f"array 1 is: \n{arr1}")
print(f"array 2 is:\n {arr2}")
print(f"addition :\n{arr1+arr2}")
print(f"substraction :\n{arr1-arr2}")
print(f"multiplication :\n{arr1*arr2}")
print(f"division :\n{arr1/arr2}")

array 1 is: 
[[ 6 10  4  7]
 [11  1 12  3]
 [ 1  9 11  9]]
array 2 is:
 [[ 2  7  4 10]
 [11  1  4  1]
 [12  6  8  6]]
addition :
[[ 8 17  8 17]
 [22  2 16  4]
 [13 15 19 15]]
substraction :
[[  4   3   0  -3]
 [  0   0   8   2]
 [-11   3   3   3]]
multiplication :
[[ 12  70  16  70]
 [121   1  48   3]
 [ 12  54  88  54]]
division :
[[3.         1.42857143 1.         0.7       ]
 [1.         1.         3.         3.        ]
 [0.08333333 1.5        1.375      1.5       ]]


In [ ]:
# 3b
arr=np.arange(1,17)
a=arr.reshape(4,4)
print(f"array:\n{a}")

print(f" sum of row:\n{a.sum(axis=1)}") #rows
print(f"sum of columns:\n{a.sum(axis=0)}") #column


array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 sum of row:
[10 26 42 58]
sum of columns:
[28 32 36 40]


In [18]:
# assignment 4,a
ar=np.random.randint(1,26,(5,5))
print(f"array:\n{ar}")
print(f"mean :\n {ar.mean()}")
print(f"median :\n {np.median(ar)}")
print(f"standard deviation :\n {ar.std()}")
print(f"variance :\n {ar.var()}")

array:
[[22  8  9 18 10]
 [25 20  3 21 13]
 [23 25  5  3  2]
 [22 11  1 13  2]
 [ 2 25 15 15  3]]
mean :
 12.64
median :
 13.0
standard deviation :
 8.394664972469121
variance :
 70.4704


In [ ]:
# 4,b
arr=np.arange(1,10)
a=arr.reshape(3,3)
print(f"array:\n{a}")
normalize=(a-a.mean())/a.std()
print(f"normalisation:\n{normalize}")

array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
normalisation:
:[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [3]:
# assignment 5
import numpy as np
ar1=np.random.randint(1,10,(3,3))
print(f"2d array:\n{ar1}")
ar=np.array([1,2,3])

#boardcasting
print(f"boardcasting:\n{ar1+ar}")

2d array:
[[8 2 6]
 [9 3 3]
 [6 7 1]]
boardcasting:
[[ 9  4  9]
 [10  5  6]
 [ 7  9  4]]


In [5]:
# 5,b substraction on column
arr=np.random.randint(1,16,(4,4))
a=np.array([1,2,3,4])
r=a.reshape(4,1)

#column boardcasting
print(f"array:\n{arr}")
print(f"substracting column:\n{arr-r}")

array:
[[ 6  9 10  6]
 [ 9 13 11 10]
 [12 11  1  9]
 [ 2 11  6  3]]
substracting column:
[[ 5  8  9  5]
 [ 7 11  9  8]
 [ 9  8 -2  6]
 [-2  7  2 -1]]


In [15]:
# assignment 6,a
a=np.random.randint(1,13,(3,3))
print("array:\n",a)
determine=np.linalg.det(a)
inverse=np.linalg.inv(a)
eigenvalue=np.linalg.eig(a)
print("determine\n",determine)
print("inverse\n",inverse)
print("eigenvalue\n",eigenvalue)

array:
 [[10 12 12]
 [ 9  9 10]
 [ 7 12 12]]
determine
 -36.0
inverse
 [[ 0.33333333  0.         -0.33333333]
 [ 1.05555556 -1.         -0.22222222]
 [-1.25        1.          0.5       ]]
eigenvalue
 EigResult(eigenvalues=array([30.76695495,  1.20448578, -0.97144073]), eigenvectors=array([[-0.63242758, -0.51323845,  0.15296495],
       [-0.52370493, -0.38889613, -0.76520462],
       [-0.57076133,  0.76507914,  0.62535079]]))


In [ ]:
#6,b
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(3,2))
print(f"array 1:\n{arr1}")
print(f"array 2:\n{arr2}")
print(f"matrix multiplication:\n{arr1@arr2}") # '@' is the operator for matrix multiplication

array 1:
[[5 4 3]
 [4 3 6]]
array 2:
[[1 8]
 [8 9]
 [7 6]]
matrix multiplication:
[[58 94]
 [70 95]]


In [21]:
# 7,a
arr=np.arange(1,10)
print(f"array:\n{arr}")
a=arr.reshape(1,9)
print(f"reshaped it to 1,9:\n{a}")
r=a.reshape(9,1)
print(f"reshaped it to 9,1:\n{r}")

array:
[1 2 3 4 5 6 7 8 9]
reshaped it to 1,9:
[[1 2 3 4 5 6 7 8 9]]
reshaped it to 9,1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [27]:
arr=np.random.randint(1,26,(5,5))
print(f"array:\n{arr}")
a=arr.reshape(25,)
print(f"flatten array:\n{a}")
r=a.reshape(5,5)
print(f"again reshaped:\n{r}")

array:
[[21 25 21 17 14]
 [16 14 23  2 14]
 [12  2 16 19  7]
 [ 2 23 18 15  2]
 [17 12  2 11 11]]
flatten array:
[21 25 21 17 14 16 14 23  2 14 12  2 16 19  7  2 23 18 15  2 17 12  2 11
 11]
again reshaped:
[[21 25 21 17 14]
 [16 14 23  2 14]
 [12  2 16 19  7]
 [ 2 23 18 15  2]
 [17 12  2 11 11]]


In [30]:
# assignment 8
arr=np.random.randint(1,26,(5,5))
print(f"array:\n{arr}")
fancy=arr[[0,0,-1,-1],[0,-1,0,-1]]
print(f"fancy indexing:\n{fancy}")

array:
[[ 6  5 17 24 19]
 [18 23 20 11 10]
 [ 4 14  3  3  9]
 [ 8 13 19 17 17]
 [18 15  7  3  5]]
fancy indexing:
[ 6 19 18  5]


In [34]:
# 8,b
arr=np.random.randint(1,26,(5,5))
print(f"array:\n{arr}")
arr[arr>10]=10        #boolean_indexing
print(f"boolean indexing:\n{arr}")

array:
[[ 9 20 12 18 13]
 [18 23  2 15 20]
 [17 10 25  4 22]
 [10  9 16  5 10]
 [19 24  7 14  6]]
boolean indexing:
[[ 9 10 10 10 10]
 [10 10  2 10 10]
 [10 10 10  4 10]
 [10  9 10  5 10]
 [10 10  7 10  6]]


In [17]:
# assignment 9
import numpy as np
data_type=[('name','U10'),('age','i4'),('weight','f4')]
data=np.array([('herald',22,57.3),('jesus',33,109),('pramod',26,61.3)],dtype=data_type)
print(f"original:\n{data}")

sorted=np.sort(data,order="name")
print(f"sorted\n{sorted}")


original:
[('herald', 22,  57.3) ('jesus', 33, 109. ) ('pramod', 26,  61.3)]
sorted
[('herald', 22,  57.3) ('jesus', 33, 109. ) ('pramod', 26,  61.3)]


In [18]:
import numpy as np

data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)

points = np.column_stack((data['x'], data['y']))

distances = np.linalg.norm(points[:, np.newaxis] - points, axis=2)

print(distances)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]
